### ISSUE TITLE
h<hmin!

### ISSUE THREAD

**Issue by DiegoGreg** [DiegoGreg/SIMBA_Troubleshooting#1]
Fehlermeldung: Problem during simulation at t=xx. Error in Integrator at time t=xx: h<hmin!

**Comment by GitHuby404** [comment]
Change Simulation settings:
--> Simulation --> Options --> Maximum consecutive hmin reached

**Comment by DiegoGreg** [comment]
Das hat sehr wahrscheinlich mit dem ausgewählten Integrator "ODE15S" zu tun.
Das Problem lässt sich beheben indem unter "Simulation" --> "Options.." die folgenden Einstellungen geändert werden:
- relative Tolerance --> reduzieren z.B. 10E-5
- absolute Tolerance --> reduzieren

Evtl. auch falls Tolerance nicht hilft:
- Maximum consecutive hmin reached --> muss man ausprobieren
